### ISSUE TITLE
Support for 5.0.1

### ISSUE THREAD

**Issue by autumncollection** [vhyza/elasticsearch-analysis-lemmagen#8]
Will be any possibility in the future to use your plugin with the newest 5.X elasticsearch? (for example 5.0.1)

**Comment by vhyza** [comment]
Hi,

to be honest, I'm not sure. Because of the license, I currently don't have use case for this plugin. On top of it, elasticsearch introduces some breaking changes when developing plugins. So I suppose there is more to do than just regenerate the plugin for elasticsearch 2.x version...I may try to take a look on it, but don't promise anything...

**Comment by autumncollection** [comment]
I found article only about small changes. For example plugin has to be within elasticsearch folder. I would be really grateful if you took a look at it.

**Comment by vhyza** [comment]
I spent most of yesterday on it and there are quite a lot of changes (especially when testing the functionality). Anyway I have functional versions for elasticsearch 5.x and 5.1.x, but there is still some work to do...

**Comment by vhyza** [comment]
Closed by https://github.com/vhyza/elasticsearch-analysis-lemmagen/commit/a0a56eac4f1db0802ece1b106d02ced4db0b1582 and https://github.com/vhyza/elasticsearch-analysis-lemmagen/commit/f5f2fb836a08d5d110dd9a561b243191d9873c48.
